apiVersion: v1
kind: Service
metadata:
  name: hrms-service
  namespace: default
  labels:
    app: hrms-app
spec:
  type: LoadBalancer
  selector:
    app: hrms-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
